# Название вашего процесса автоматизации. Оно будет отображаться в GitHub.
name: .NET Build and Test

# Триггеры: когда запускать этот процесс.
on:
  # Запускать при каждом push в ветку main
  push:
    branches: [ "main" ]
  # Запускать при создании Pull Request, который нацелен на ветку main
  pull_request:
    branches: [ "main" ]

# Задачи: что именно нужно сделать.
jobs:
  # Мы определяем одну задачу с названием build-and-test
  build-and-test:
    # На какой операционной системе запускать. ubuntu-latest - быстрый и бесплатный.
    runs-on: ubuntu-latest

    # Шаги: последовательность команд, которые нужно выполнить.
    steps:
    # 1. Клонирование вашего репозитория на виртуальную машину
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Установка нужной версии .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Укажите здесь вашу версию .NET. Например, '8.0.x' или '7.0.x'
        dotnet-version: '9.0.x'

    # 3. Восстановление зависимостей (NuGet пакетов) для всего решения
    - name: Restore dependencies
      run: dotnet restore

    # 4. Сборка всего решения в режиме Release.
    # Флаг --no-restore говорит не восстанавливать пакеты снова, т.к. мы это сделали на прошлом шаге.
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # 5. Запуск всех тестов в решении.
    # Флаг --no-build говорит не собирать проект заново.
    - name: Test
      run: dotnet test --no-build --verbosity normal